/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author Examen Práctico #1
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonPuntosCU = new javax.swing.JButton();
        botonPuntosFuncion = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");
        setMaximumSize(new java.awt.Dimension(455, 480));
        setMinimumSize(new java.awt.Dimension(455, 480));
        setPreferredSize(new java.awt.Dimension(455, 480));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonPuntosCU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/botonCP.png"))); // NOI18N
        botonPuntosCU.setBorder(null);
        botonPuntosCU.setBorderPainted(false);
        botonPuntosCU.setContentAreaFilled(false);
        botonPuntosCU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonPuntosCU.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/botonCPG.png"))); // NOI18N
        botonPuntosCU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPuntosCUActionPerformed(evt);
            }
        });
        getContentPane().add(botonPuntosCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 200, 80));

        botonPuntosFuncion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/botonPF.png"))); // NOI18N
        botonPuntosFuncion.setBorder(null);
        botonPuntosFuncion.setBorderPainted(false);
        botonPuntosFuncion.setContentAreaFilled(false);
        botonPuntosFuncion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonPuntosFuncion.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/botonPFG.png"))); // NOI18N
        botonPuntosFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPuntosFuncionActionPerformed(evt);
            }
        });
        getContentPane().add(botonPuntosFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 200, 80));

        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/button-salir.png"))); // NOI18N
        botonSalir.setBorder(null);
        botonSalir.setBorderPainted(false);
        botonSalir.setContentAreaFilled(false);
        botonSalir.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/button-salirCH.png"))); // NOI18N
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondoPrincipal.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPuntosCUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuntosCUActionPerformed
        VentanaPuntosdeCUAW ventana = new VentanaPuntosdeCUAW();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonPuntosCUActionPerformed

    private void botonPuntosFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuntosFuncionActionPerformed
        VentanaPuntosdeFuncionPuntosdeFuncionSinAjustar ventana1 = new VentanaPuntosdeFuncionPuntosdeFuncionSinAjustar();
        ventana1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonPuntosFuncionActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        JOptionPane.showMessageDialog(this, "\nDESARROLLADO POR:\n" + "Francisco Apodaca #35675\nLeobardo Peréz #109037");
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPuntosCU;
    private javax.swing.JButton botonPuntosFuncion;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
