/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Examen Práctico #1
 */
public class VentanaPuntosdeFuncionPuntosdeFuncionSinAjustar extends javax.swing.JFrame {

    private int puntosEntradas;
    private int puntosSalidas;
    private int puntosConsultas;
    private int puntosArchivos;
    private int puntosInterfaces;
    private double PF;

    /**
     * Creates new form VentanaPuntosdeFuncion
     */
    public VentanaPuntosdeFuncionPuntosdeFuncionSinAjustar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void calcularEntradas() {
        int entradaS = Integer.parseInt(txtEntradaSimple.getText());
        int entradaP = Integer.parseInt(txtEntradaPromedio.getText());
        int entradaC = Integer.parseInt(txtEntradaComplejo.getText());
        int resultS = entradaS;
        int resultP = entradaP;
        int resultC = entradaC;

        if (entradaS != 0) {
            resultS = entradaS * 3;
        }
        if (entradaP != 0) {
            resultP = entradaP * 4;
        }
        if (entradaC != 0) {
            resultC = entradaC * 6;
        }
        puntosEntradas = resultS + resultP + resultC;
        txtPuntosEntrada.setText(new Integer(puntosEntradas).toString());
    }

    public void calcularSalidas() {
        int salidaS = Integer.parseInt(txtSalidaSimple.getText());
        int salidaP = Integer.parseInt(txtSalidaPromedio.getText());
        int salidaC = Integer.parseInt(txtSalidaComplejo.getText());
        int resultS = salidaS;
        int resultP = salidaP;
        int resultC = salidaC;

        if (salidaS != 0) {
            resultS = salidaS * 4;
        }
        if (salidaP != 0) {
            resultP = salidaP * 5;
        }
        if (salidaC != 0) {
            resultC = salidaC * 7;
        }
        puntosSalidas = resultS + resultP + resultC;
        txtPuntosSalidas.setText(new Integer(puntosSalidas).toString());
    }

    public void calcularConsultas() {
        int consultaS = Integer.parseInt(txtConsultaSimple.getText());
        int consultaP = Integer.parseInt(txtConsultaPromedio.getText());
        int consultaC = Integer.parseInt(txtConsultaComplejo.getText());
        int resultS = consultaS;
        int resultP = consultaP;
        int resultC = consultaC;

        if (consultaS != 0) {
            resultS = consultaS * 3;
        }
        if (consultaP != 0) {
            resultP = consultaP * 4;
        }
        if (consultaC != 0) {
            resultC = consultaC * 6;
        }
        puntosConsultas = resultS + resultP + resultC;
        txtPuntosConsultas.setText(new Integer(puntosConsultas).toString());

    }

    public void calcularArchivos() {
        int archivoS = Integer.parseInt(txtArchivoSimple.getText());
        int archivoP = Integer.parseInt(txtArchivoPromedio.getText());
        int archivoC = Integer.parseInt(txtArchivoComplejo.getText());
        int resultS = archivoS;
        int resultP = archivoP;
        int resultC = archivoC;

        if (archivoS != 0) {
            resultS = archivoS * 7;
        }
        if (archivoP != 0) {
            resultP = archivoP * 10;
        }
        if (archivoC != 0) {
            resultC = archivoC * 15;
        }
        puntosArchivos = resultS + resultP + resultC;
        txtPuntosArchivos.setText(new Integer(puntosArchivos).toString());

    }

    public void calcularInterfaces() {
        int interfacesS = Integer.parseInt(txtInterfazSimple.getText());
        int interfacesP = Integer.parseInt(txtInterfazPromedio.getText());
        int interfacesC = Integer.parseInt(txtInterfazComplejo.getText());
        int resultS = interfacesS;
        int resultP = interfacesP;
        int resultC = interfacesC;

        if (interfacesS != 0) {
            resultS = interfacesS * 5;
        }
        if (interfacesP != 0) {
            resultP = interfacesP * 7;
        }
        if (interfacesP != 0) {
            resultC = interfacesP * 10;
        }
        puntosInterfaces = resultS + resultP + resultC;
        txtPuntosInterfaces.setText(new Integer(puntosInterfaces).toString());

    }

    public void calcularPuntosdeFuncionSinAjustar() {
        PF = puntosEntradas + puntosSalidas + puntosArchivos + puntosConsultas + puntosInterfaces;
        txtTotal.setText(Double.toString(PF));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtEntradaSimple = new javax.swing.JTextField();
        txtEntradaPromedio = new javax.swing.JTextField();
        txtEntradaComplejo = new javax.swing.JTextField();
        txtPuntosEntrada = new javax.swing.JTextField();
        txtSalidaPromedio = new javax.swing.JTextField();
        txtSalidaSimple = new javax.swing.JTextField();
        txtSalidaComplejo = new javax.swing.JTextField();
        txtPuntosSalidas = new javax.swing.JTextField();
        txtConsultaSimple = new javax.swing.JTextField();
        txtConsultaPromedio = new javax.swing.JTextField();
        txtConsultaComplejo = new javax.swing.JTextField();
        txtPuntosConsultas = new javax.swing.JTextField();
        txtArchivoSimple = new javax.swing.JTextField();
        txtArchivoPromedio = new javax.swing.JTextField();
        txtArchivoComplejo = new javax.swing.JTextField();
        txtPuntosArchivos = new javax.swing.JTextField();
        txtInterfazSimple = new javax.swing.JTextField();
        txtInterfazPromedio = new javax.swing.JTextField();
        txtInterfazComplejo = new javax.swing.JTextField();
        txtPuntosInterfaces = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        botonCalcular = new javax.swing.JButton();
        botonSiguiente = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULO PUNTOS DE FUNCIÓN SIN AJUSTAR");
        setMaximumSize(new java.awt.Dimension(720, 580));
        setMinimumSize(new java.awt.Dimension(720, 580));
        setPreferredSize(new java.awt.Dimension(720, 580));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ELEMENTOS:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Entradas");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Salidas");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Consultas");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Archivos");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("SIMPLE");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("PROMEDIO");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Interfaces");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("COMPLEJO");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("PUNTOS");

        txtEntradaSimple.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEntradaSimple.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEntradaSimple.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtEntradaSimple.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEntradaSimpleKeyTyped(evt);
            }
        });

        txtEntradaPromedio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEntradaPromedio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEntradaPromedio.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtEntradaPromedio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEntradaPromedioKeyTyped(evt);
            }
        });

        txtEntradaComplejo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEntradaComplejo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEntradaComplejo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtEntradaComplejo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEntradaComplejoKeyTyped(evt);
            }
        });

        txtPuntosEntrada.setEditable(false);
        txtPuntosEntrada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPuntosEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPuntosEntrada.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtPuntosEntrada.setFocusable(false);

        txtSalidaPromedio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSalidaPromedio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSalidaPromedio.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtSalidaPromedio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSalidaPromedioKeyTyped(evt);
            }
        });

        txtSalidaSimple.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSalidaSimple.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSalidaSimple.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtSalidaSimple.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSalidaSimpleKeyTyped(evt);
            }
        });

        txtSalidaComplejo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSalidaComplejo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSalidaComplejo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtSalidaComplejo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSalidaComplejoKeyTyped(evt);
            }
        });

        txtPuntosSalidas.setEditable(false);
        txtPuntosSalidas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPuntosSalidas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPuntosSalidas.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtPuntosSalidas.setFocusable(false);

        txtConsultaSimple.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtConsultaSimple.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtConsultaSimple.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtConsultaSimple.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConsultaSimpleKeyTyped(evt);
            }
        });

        txtConsultaPromedio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtConsultaPromedio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtConsultaPromedio.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtConsultaPromedio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConsultaPromedioKeyTyped(evt);
            }
        });

        txtConsultaComplejo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtConsultaComplejo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtConsultaComplejo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtConsultaComplejo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConsultaComplejoKeyTyped(evt);
            }
        });

        txtPuntosConsultas.setEditable(false);
        txtPuntosConsultas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPuntosConsultas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPuntosConsultas.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtPuntosConsultas.setFocusable(false);

        txtArchivoSimple.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtArchivoSimple.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtArchivoSimple.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtArchivoSimple.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtArchivoSimpleKeyTyped(evt);
            }
        });

        txtArchivoPromedio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtArchivoPromedio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtArchivoPromedio.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtArchivoPromedio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtArchivoPromedioKeyTyped(evt);
            }
        });

        txtArchivoComplejo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtArchivoComplejo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtArchivoComplejo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtArchivoComplejo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtArchivoComplejoKeyTyped(evt);
            }
        });

        txtPuntosArchivos.setEditable(false);
        txtPuntosArchivos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPuntosArchivos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPuntosArchivos.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtPuntosArchivos.setFocusable(false);

        txtInterfazSimple.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtInterfazSimple.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInterfazSimple.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtInterfazSimple.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInterfazSimpleKeyTyped(evt);
            }
        });

        txtInterfazPromedio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtInterfazPromedio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInterfazPromedio.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtInterfazPromedio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInterfazPromedioKeyTyped(evt);
            }
        });

        txtInterfazComplejo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtInterfazComplejo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInterfazComplejo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtInterfazComplejo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInterfazComplejoKeyTyped(evt);
            }
        });

        txtPuntosInterfaces.setEditable(false);
        txtPuntosInterfaces.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPuntosInterfaces.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPuntosInterfaces.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtPuntosInterfaces.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtArchivoSimple, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEntradaSimple, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSalidaSimple)
                    .addComponent(txtConsultaSimple, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtInterfazSimple))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtConsultaPromedio, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                            .addComponent(txtSalidaPromedio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEntradaPromedio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtArchivoPromedio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtInterfazPromedio, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(44, 44, 44))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel12)
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtConsultaComplejo, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                            .addComponent(txtSalidaComplejo)
                            .addComponent(txtEntradaComplejo)
                            .addComponent(txtArchivoComplejo)
                            .addComponent(txtInterfazComplejo))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPuntosEntrada)
                            .addComponent(txtPuntosSalidas)
                            .addComponent(txtPuntosConsultas)
                            .addComponent(txtPuntosArchivos)
                            .addComponent(txtPuntosInterfaces, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(53, 53, 53))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel7))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEntradaSimple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEntradaPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEntradaComplejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPuntosEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSalidaSimple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSalidaComplejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSalidaPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtConsultaSimple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConsultaPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConsultaComplejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPuntosConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtArchivoSimple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArchivoPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArchivoComplejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPuntosArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtPuntosSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtInterfazSimple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInterfazPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInterfazComplejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPuntosInterfaces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 650, 290));

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(255, 255, 255));
        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtTotal.setFocusable(false);
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 110, 40));

        botonCalcular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonCalcular.setText("Obtener");
        botonCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(botonCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, 40));

        botonSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/botonSiguiente.png"))); // NOI18N
        botonSiguiente.setBorder(null);
        botonSiguiente.setBorderPainted(false);
        botonSiguiente.setContentAreaFilled(false);
        botonSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSiguiente.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/botonSiguienteG.png"))); // NOI18N
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(botonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 420, 80, 100));

        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/volverMenuPrincipal.png"))); // NOI18N
        botonVolver.setBorder(null);
        botonVolver.setBorderPainted(false);
        botonVolver.setContentAreaFilled(false);
        botonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolver.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/volverMenuPrincipalG.png"))); // NOI18N
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("INGRESE LOS DATOS EN LA TABLA SIGUIENTE");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondo.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularActionPerformed
        if (txtEntradaSimple.getText().isEmpty() || txtEntradaPromedio.getText().isEmpty() || txtEntradaComplejo.getText().isEmpty() || txtArchivoComplejo.getText().isEmpty()
                || txtArchivoPromedio.getText().isEmpty() || txtArchivoSimple.getText().isEmpty() || txtConsultaComplejo.getText().isEmpty() || txtConsultaPromedio.getText().isEmpty()
                || txtConsultaSimple.getText().isEmpty() || txtInterfazComplejo.getText().isEmpty() || txtInterfazPromedio.getText().isEmpty() || txtInterfazSimple.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Verifique que no existan campos vacios");
        } else {
            calcularEntradas();
            calcularSalidas();
            calcularArchivos();
            calcularConsultas();
            calcularInterfaces();
            calcularPuntosdeFuncionSinAjustar();
        }

    }//GEN-LAST:event_botonCalcularActionPerformed

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        if (txtTotal.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe obtener el calculo de los puntos de función sin ajustar");
        } else {
            VentanaPuntosdeFuncionFactordeAjuste vpffa = new VentanaPuntosdeFuncionFactordeAjuste();
            vpffa.setVisible(true);
            vpffa.getTxtPFsinAjustar().setText(txtTotal.getText());
            vpffa.getTxtPFsinAjustar().setVisible(false);
            this.dispose();
        }

    }//GEN-LAST:event_botonSiguienteActionPerformed

    private void txtEntradaSimpleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEntradaSimpleKeyTyped
        validacionNumeros(evt);
    }//GEN-LAST:event_txtEntradaSimpleKeyTyped

    private void txtEntradaPromedioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEntradaPromedioKeyTyped
        validacionNumeros(evt);
    }//GEN-LAST:event_txtEntradaPromedioKeyTyped

    private void txtEntradaComplejoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEntradaComplejoKeyTyped
        validacionNumeros(evt);
    }//GEN-LAST:event_txtEntradaComplejoKeyTyped

    private void txtSalidaSimpleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalidaSimpleKeyTyped
        validacionNumeros(evt);
    }//GEN-LAST:event_txtSalidaSimpleKeyTyped

    private void txtSalidaPromedioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalidaPromedioKeyTyped
        validacionNumeros(evt);
    }//GEN-LAST:event_txtSalidaPromedioKeyTyped

    private void txtSalidaComplejoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalidaComplejoKeyTyped
        validacionNumeros(evt);
    }//GEN-LAST:event_txtSalidaComplejoKeyTyped

    private void txtConsultaSimpleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultaSimpleKeyTyped
        validacionNumeros(evt);
    }//GEN-LAST:event_txtConsultaSimpleKeyTyped

    private void txtConsultaPromedioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultaPromedioKeyTyped
        validacionNumeros(evt);
    }//GEN-LAST:event_txtConsultaPromedioKeyTyped

    private void txtConsultaComplejoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultaComplejoKeyTyped
        validacionNumeros(evt);
    }//GEN-LAST:event_txtConsultaComplejoKeyTyped

    private void txtArchivoSimpleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtArchivoSimpleKeyTyped
        validacionNumeros(evt);
    }//GEN-LAST:event_txtArchivoSimpleKeyTyped

    private void txtArchivoPromedioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtArchivoPromedioKeyTyped
        validacionNumeros(evt);
    }//GEN-LAST:event_txtArchivoPromedioKeyTyped

    private void txtArchivoComplejoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtArchivoComplejoKeyTyped
        validacionNumeros(evt);
    }//GEN-LAST:event_txtArchivoComplejoKeyTyped

    private void txtInterfazSimpleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInterfazSimpleKeyTyped
        validacionNumeros(evt);
    }//GEN-LAST:event_txtInterfazSimpleKeyTyped

    private void txtInterfazPromedioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInterfazPromedioKeyTyped
        validacionNumeros(evt);
    }//GEN-LAST:event_txtInterfazPromedioKeyTyped

    private void txtInterfazComplejoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInterfazComplejoKeyTyped
        validacionNumeros(evt);
    }//GEN-LAST:event_txtInterfazComplejoKeyTyped

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        VentanaPrincipal vp = new VentanaPrincipal();
        vp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    public void validacionNumeros(java.awt.event.KeyEvent evt) {
        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se permiten números");
        }
    }

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalcular;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtArchivoComplejo;
    private javax.swing.JTextField txtArchivoPromedio;
    private javax.swing.JTextField txtArchivoSimple;
    private javax.swing.JTextField txtConsultaComplejo;
    private javax.swing.JTextField txtConsultaPromedio;
    private javax.swing.JTextField txtConsultaSimple;
    private javax.swing.JTextField txtEntradaComplejo;
    private javax.swing.JTextField txtEntradaPromedio;
    private javax.swing.JTextField txtEntradaSimple;
    private javax.swing.JTextField txtInterfazComplejo;
    private javax.swing.JTextField txtInterfazPromedio;
    private javax.swing.JTextField txtInterfazSimple;
    private javax.swing.JTextField txtPuntosArchivos;
    private javax.swing.JTextField txtPuntosConsultas;
    private javax.swing.JTextField txtPuntosEntrada;
    private javax.swing.JTextField txtPuntosInterfaces;
    private javax.swing.JTextField txtPuntosSalidas;
    private javax.swing.JTextField txtSalidaComplejo;
    private javax.swing.JTextField txtSalidaPromedio;
    private javax.swing.JTextField txtSalidaSimple;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getTxtTotal() {
        return txtTotal;
    }

    public void setTxtTotal(javax.swing.JTextField txtTotal) {
        this.txtTotal = txtTotal;
    }
}
