/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Francisco Apodaca
 */
public class VentanaResultadosPuntosdeFuncion extends javax.swing.JFrame {

    private double gi;
    private double pf;
    private double resultadoGI;
    private double resultado;
    DecimalFormat df = new DecimalFormat("###.###");

    /**
     * Creates new form VentanaFactordeAjuste
     */
    public VentanaResultadosPuntosdeFuncion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public JTextField getTxtPuntosSinAjustar() {
        return txtPuntosSinAjustar;
    }

    public void setTxtPuntosSinAjustar(JTextField txtPuntosSinAjustar) {
        this.txtPuntosSinAjustar = txtPuntosSinAjustar;
    }

    public JTextField getTxtGI() {
        return txtGI;
    }

    public void setTxtGI(JTextField txtGI) {
        this.txtGI = txtGI;
    }

    public void calcularFactordeAjuste() {
        gi = Double.parseDouble(txtGI.getText());
        resultadoGI = (gi * 0.01) + 0.65;
        String fresult = df.format(resultadoGI);
        txtFactordeAjuste.setText(fresult);
    }

    public void calcularPuntosdeFuncion() {
        pf = Double.parseDouble(txtPuntosSinAjustar.getText());
        double resultado = (pf * resultadoGI);
        String fresult = df.format(resultado);
        txtPuntosdeFuncion.setText(fresult);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPuntosSinAjustar = new javax.swing.JTextField();
        txtGI = new javax.swing.JTextField();
        txtFactordeAjuste = new javax.swing.JTextField();
        txtPuntosdeFuncion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboBoxLineas = new javax.swing.JComboBox();
        txtLineasdeCodigo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULO PUNTOS DE FUNCIÓN Y LINEAS DE CÓDIGO");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FACTOR DE AJUSTE:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PUNTOS DE FUNCIÓN:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Puntos de función sin ajustar:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 31, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GI:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        txtPuntosSinAjustar.setEditable(false);
        txtPuntosSinAjustar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtPuntosSinAjustar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPuntosSinAjustar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtPuntosSinAjustar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPuntosSinAjustar.setFocusable(false);
        getContentPane().add(txtPuntosSinAjustar, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 31, 158, -1));

        txtGI.setEditable(false);
        txtGI.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtGI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGI.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtGI.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtGI.setFocusable(false);
        getContentPane().add(txtGI, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 158, -1));

        txtFactordeAjuste.setEditable(false);
        txtFactordeAjuste.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtFactordeAjuste.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFactordeAjuste.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtFactordeAjuste.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtFactordeAjuste.setFocusable(false);
        getContentPane().add(txtFactordeAjuste, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 210, -1));

        txtPuntosdeFuncion.setEditable(false);
        txtPuntosdeFuncion.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtPuntosdeFuncion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPuntosdeFuncion.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtPuntosdeFuncion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPuntosdeFuncion.setFocusable(false);
        getContentPane().add(txtPuntosdeFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 200, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Líneas de código:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, -1));

        comboBoxLineas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        comboBoxLineas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ensamblador", "C", "C++", "Fortan", "Pascal", "Java", "Generadores de código", "Spreadsheet", "Lenguajes gráficos (iconos)" }));
        comboBoxLineas.setSelectedIndex(5);
        comboBoxLineas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboBoxLineas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxLineasActionPerformed(evt);
            }
        });
        getContentPane().add(comboBoxLineas, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 240, -1));

        txtLineasdeCodigo.setEditable(false);
        txtLineasdeCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtLineasdeCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLineasdeCodigo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtLineasdeCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLineasdeCodigo.setFocusable(false);
        getContentPane().add(txtLineasdeCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 176, 39));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setText("Calcular");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 190, 50));

        botonVolver.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonVolver.setText("Aceptar");
        botonVolver.setBorder(null);
        botonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 130, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondo3.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        calcularFactordeAjuste();
        calcularPuntosdeFuncion();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboBoxLineasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxLineasActionPerformed
        if (comboBoxLineas.getSelectedItem().equals("Ensamblador")) {
            double psa = Double.parseDouble(txtPuntosSinAjustar.getText());
            resultado = psa * 320;
            txtLineasdeCodigo.setText(new Double(resultado).toString());
        }
        if (comboBoxLineas.getSelectedItem().equals("C")) {
            double psa = Double.parseDouble(txtPuntosSinAjustar.getText());
            resultado = psa * 128;
            txtLineasdeCodigo.setText(new Double(resultado).toString());
        }
        if (comboBoxLineas.getSelectedItem().equals("C++")) {
            double psa = Double.parseDouble(txtPuntosSinAjustar.getText());
            resultado = psa * 29;
            txtLineasdeCodigo.setText(new Double(resultado).toString());
        }
        if (comboBoxLineas.getSelectedItem().equals("Fortan")) {
            double psa = Double.parseDouble(txtPuntosSinAjustar.getText());
            resultado = psa * 105;
            txtLineasdeCodigo.setText(new Double(resultado).toString());
        }
        if (comboBoxLineas.getSelectedItem().equals("Pascal")) {
            double psa = Double.parseDouble(txtPuntosSinAjustar.getText());
            resultado = psa * 91;
            txtLineasdeCodigo.setText(new Double(resultado).toString());
        }
        if (comboBoxLineas.getSelectedItem().equals("Java")) {
            double psa = Double.parseDouble(txtPuntosSinAjustar.getText());
            resultado = psa * 30;
            txtLineasdeCodigo.setText(new Double(resultado).toString());
        }
        if (comboBoxLineas.getSelectedItem().equals("Generadores de código")) {
            double psa = Double.parseDouble(txtPuntosSinAjustar.getText());
            resultado = psa * 15;
            txtLineasdeCodigo.setText(new Double(resultado).toString());
        }
        if (comboBoxLineas.getSelectedItem().equals("Spreadsheet")) {
            double psa = Double.parseDouble(txtPuntosSinAjustar.getText());
            resultado = psa * 6;
            txtLineasdeCodigo.setText(new Double(resultado).toString());
        }
        if (comboBoxLineas.getSelectedItem().equals("Lenguajes gráficos")) {
            double psa = Double.parseDouble(txtPuntosSinAjustar.getText());
            resultado = psa * 4;
            txtLineasdeCodigo.setText(new Double(resultado).toString());
        }

    }//GEN-LAST:event_comboBoxLineasActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        VentanaPrincipal vp = new VentanaPrincipal();
        vp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVolver;
    private javax.swing.JComboBox comboBoxLineas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtFactordeAjuste;
    private javax.swing.JTextField txtGI;
    private javax.swing.JTextField txtLineasdeCodigo;
    private javax.swing.JTextField txtPuntosSinAjustar;
    private javax.swing.JTextField txtPuntosdeFuncion;
    // End of variables declaration//GEN-END:variables
}
