/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.JTextField;

/**
 *
 * @author Francisco Apodaca
 */
public class VentanaPuntosdeCUUCW extends javax.swing.JFrame {

    private int resultadoS;
    private int resultadoP;
    private int resultadoC;

    /**
     * Creates new form VentanaPuntosdeCU
     */
    public VentanaPuntosdeCUUCW() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        etiqueta1 = new javax.swing.JLabel();
        etiqueta2 = new javax.swing.JLabel();
        etiqueta3 = new javax.swing.JLabel();
        txtCUSimple = new javax.swing.JTextField();
        txtCUPromedio = new javax.swing.JTextField();
        totalComplejo = new javax.swing.JTextField();
        totalSimple = new javax.swing.JTextField();
        totalPromedio = new javax.swing.JTextField();
        totalUCW = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCUComplejo = new javax.swing.JTextField();
        botonCalcular = new javax.swing.JButton();
        botonSiguiente = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtAWS = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DETERMINACIÓN DEL FACTOR DE PESO EN LOS CASOS DE USO SIN AJUSTAR (UCW)");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Tipo de caso de uso:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Descripción:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Factor de Peso:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Número de CU:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(133, 133, 133)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(38, 38, 38)
                .addComponent(jLabel20)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 770, 40));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Resultado:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel17)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 150, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Simple");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Promedio");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Complejo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("• 3 o menos transacciones");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("• 3 a 7 transacciones");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 170, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("• Se hace el caso de uso con ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("5 a 10 objetos de análisis");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("• Más de 7 transacciones");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("más de 10 objetos de análisis");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        etiqueta1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        etiqueta1.setText("5");
        getContentPane().add(etiqueta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, -1));

        etiqueta2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        etiqueta2.setText("10");
        getContentPane().add(etiqueta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));

        etiqueta3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        etiqueta3.setText("15");
        getContentPane().add(etiqueta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, -1));

        txtCUSimple.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCUSimple.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtCUSimple, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 100, -1));

        txtCUPromedio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCUPromedio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCUPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCUPromedioActionPerformed(evt);
            }
        });
        getContentPane().add(txtCUPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 100, -1));

        totalComplejo.setEditable(false);
        totalComplejo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalComplejo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalComplejo.setFocusable(false);
        getContentPane().add(totalComplejo, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, 100, -1));

        totalSimple.setEditable(false);
        totalSimple.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalSimple.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalSimple.setFocusable(false);
        getContentPane().add(totalSimple, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 100, -1));

        totalPromedio.setEditable(false);
        totalPromedio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalPromedio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalPromedio.setFocusable(false);
        totalPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPromedioActionPerformed(evt);
            }
        });
        getContentPane().add(totalPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 170, 100, -1));

        totalUCW.setEditable(false);
        totalUCW.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        totalUCW.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalUCW.setFocusable(false);
        getContentPane().add(totalUCW, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 110, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setText("TOTAL UCW:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, -1, -1));

        txtCUComplejo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCUComplejo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtCUComplejo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 100, -1));

        botonCalcular.setText("Calcular");
        botonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(botonCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 380, -1, -1));

        botonSiguiente.setText("Siguiente");
        getContentPane().add(botonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 410, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("• Se hace el caso de uso con ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("menos de 5 objetos de análisis");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("• Se hace el caso de uso con ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));
        getContentPane().add(txtAWS, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 422, 90, 30));

        jLabel14.setText("TOTAL AW:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void calcularCUSimple() {
        int numCUS = Integer.parseInt(txtCUSimple.getText().toString());
        resultadoS = numCUS * 5;
        totalSimple.setText((new Integer(resultadoS).toString()));
    }

    public void calcularCUPromedio() {
        int numCUP = Integer.parseInt(txtCUPromedio.getText().toString());
        resultadoP = numCUP * 10;
        totalPromedio.setText((new Integer(resultadoP).toString()));
    }

    public void calcularCUComplejo() {
        int numCUC = Integer.parseInt(txtCUComplejo.getText().toString());
        resultadoC = numCUC * 15;
        totalComplejo.setText((new Integer(resultadoC).toString()));
    }

    public void calculoUCW() {
        int suma = resultadoS + resultadoP + resultadoC;
        totalUCW.setText((new Integer(suma).toString()));
    }

    public JTextField getTxtAWS() {
        return txtAWS;
    }

    public void setTxtAWS(JTextField txtAWS) {
        this.txtAWS = txtAWS;
    }
    
    
    private void txtCUPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCUPromedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCUPromedioActionPerformed

    private void totalPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPromedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalPromedioActionPerformed

    private void botonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularActionPerformed
        calcularCUComplejo();
        calcularCUPromedio();
        calcularCUSimple();
        calculoUCW();
    }//GEN-LAST:event_botonCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPuntosdeCUUCW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPuntosdeCUUCW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPuntosdeCUUCW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPuntosdeCUUCW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPuntosdeCUUCW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalcular;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JLabel etiqueta1;
    private javax.swing.JLabel etiqueta2;
    private javax.swing.JLabel etiqueta3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField totalComplejo;
    private javax.swing.JTextField totalPromedio;
    private javax.swing.JTextField totalSimple;
    private javax.swing.JTextField totalUCW;
    private javax.swing.JTextField txtAWS;
    private javax.swing.JTextField txtCUComplejo;
    private javax.swing.JTextField txtCUPromedio;
    private javax.swing.JTextField txtCUSimple;
    // End of variables declaration//GEN-END:variables
}
