/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.JTextField;

/**
 *
 * @author Francisco Apodaca
 */
public class VentanaResultados extends javax.swing.JFrame {

    private double gi;
    private double pf;
    private double resultadoGI;
    private double resultado;

    /**
     * Creates new form VentanaFactordeAjuste
     */
    public VentanaResultados() {
        initComponents();

    }

    public JTextField getTxtPuntosSinAjustar() {
        return txtPuntosSinAjustar;
    }

    public void setTxtPuntosSinAjustar(JTextField txtPuntosSinAjustar) {
        this.txtPuntosSinAjustar = txtPuntosSinAjustar;
    }

    public JTextField getTxtGI() {
        return txtGI;
    }

    public void setTxtGI(JTextField txtGI) {
        this.txtGI = txtGI;
    }

    public void calcularFactordeAjuste() {
        gi = Double.parseDouble(txtGI.getText());
        resultadoGI = (gi * 0.01) + 0.65;
        txtFactordeAjuste.setText(new Double(resultadoGI).toString());
    }

    public void calcularPuntosdeFuncion() {
        pf = Double.parseDouble(txtPuntosSinAjustar.getText());
        double resultado = (pf * resultadoGI);
        double redondear = Math.rint(resultado);
        txtPuntosdeFuncion.setText(new Double(redondear).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPuntosSinAjustar = new javax.swing.JTextField();
        txtGI = new javax.swing.JTextField();
        txtFactordeAjuste = new javax.swing.JTextField();
        txtPuntosdeFuncion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboBoxLineas = new javax.swing.JComboBox();
        txtLineasdeCodigo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("FACTOR DE AJUSTE:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("PUNTOS DE FUNCIÓN:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Puntos de función sin ajustar:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("GI:");

        txtPuntosSinAjustar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtPuntosSinAjustar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPuntosSinAjustar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtGI.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtGI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGI.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtFactordeAjuste.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtFactordeAjuste.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFactordeAjuste.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtPuntosdeFuncion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtPuntosdeFuncion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPuntosdeFuncion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Líneas de código:");

        comboBoxLineas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ensamblador", "C", "C++", "Fortan", "Pascal", "Java", "Generadores de código", "Spreadsheet", "Lenguajes gráficos (iconos)" }));
        comboBoxLineas.setSelectedIndex(5);
        comboBoxLineas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxLineasActionPerformed(evt);
            }
        });

        txtLineasdeCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLineasdeCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(comboBoxLineas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPuntosSinAjustar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGI, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtLineasdeCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(303, 303, 303))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(377, 377, 377))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(txtFactordeAjuste, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtPuntosdeFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtPuntosSinAjustar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(51, 51, 51)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFactordeAjuste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPuntosdeFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboBoxLineas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtLineasdeCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        calcularFactordeAjuste();
        calcularPuntosdeFuncion();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboBoxLineasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxLineasActionPerformed
        if (comboBoxLineas.getSelectedItem().equals("Ensamblador")) {
            double psa = Double.parseDouble(txtPuntosSinAjustar.getText());
            resultado = psa * 320;
            txtLineasdeCodigo.setText(new Double(resultado).toString());
        }
        if (comboBoxLineas.getSelectedItem().equals("C")) {
            double psa = Double.parseDouble(txtPuntosSinAjustar.getText());
            resultado = psa * 128;
            txtLineasdeCodigo.setText(new Double(resultado).toString());
        }
        if (comboBoxLineas.getSelectedItem().equals("C++")) {
            double psa = Double.parseDouble(txtPuntosSinAjustar.getText());
            resultado = psa * 29;
            txtLineasdeCodigo.setText(new Double(resultado).toString());
        }
        if (comboBoxLineas.getSelectedItem().equals("Fortan")) {
            double psa = Double.parseDouble(txtPuntosSinAjustar.getText());
            resultado = psa * 105;
            txtLineasdeCodigo.setText(new Double(resultado).toString());
        }
        if (comboBoxLineas.getSelectedItem().equals("Pascal")) {
            double psa = Double.parseDouble(txtPuntosSinAjustar.getText());
            resultado = psa * 91;
            txtLineasdeCodigo.setText(new Double(resultado).toString());
        }
        if (comboBoxLineas.getSelectedItem().equals("Java")) {
            double psa = Double.parseDouble(txtPuntosSinAjustar.getText());
            resultado = psa * 30;
            txtLineasdeCodigo.setText(new Double(resultado).toString());
        }
        if (comboBoxLineas.getSelectedItem().equals("Generadores de código")) {
            double psa = Double.parseDouble(txtPuntosSinAjustar.getText());
            resultado = psa * 15;
            txtLineasdeCodigo.setText(new Double(resultado).toString());
        }
        if (comboBoxLineas.getSelectedItem().equals("Spreadsheet")) {
            double psa = Double.parseDouble(txtPuntosSinAjustar.getText());
            resultado = psa * 6;
            txtLineasdeCodigo.setText(new Double(resultado).toString());
        }
        if (comboBoxLineas.getSelectedItem().equals("Lenguajes gráficos (iconos)")) {
            double psa = Double.parseDouble(txtPuntosSinAjustar.getText());
            resultado = psa * 4;
            txtLineasdeCodigo.setText(new Double(resultado).toString());
        }

    }//GEN-LAST:event_comboBoxLineasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaResultados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboBoxLineas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtFactordeAjuste;
    private javax.swing.JTextField txtGI;
    private javax.swing.JTextField txtLineasdeCodigo;
    private javax.swing.JTextField txtPuntosSinAjustar;
    private javax.swing.JTextField txtPuntosdeFuncion;
    // End of variables declaration//GEN-END:variables
}
