/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.JTextField;

/**
 *
 * @author Examen Práctico #1
 */
public class VentanaPuntosdeFuncionFactordeAjuste extends javax.swing.JFrame {

    private double suma;

    /**
     * Creates new form VentanaPuntosdeFuncionFactordeAjuste
     */
    public VentanaPuntosdeFuncionFactordeAjuste() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtPFsinAjustar.setVisible(false);
     
    }

    public void calculoGI() {
        int num1 = Integer.parseInt((String) combo1.getSelectedItem());
        int num2 = Integer.parseInt((String) combo2.getSelectedItem());
        int num3 = Integer.parseInt((String) combo3.getSelectedItem());
        int num4 = Integer.parseInt((String) combo4.getSelectedItem());
        int num5 = Integer.parseInt((String) combo5.getSelectedItem());
        int num6 = Integer.parseInt((String) combo6.getSelectedItem());
        int num7 = Integer.parseInt((String) combo7.getSelectedItem());
        int num8 = Integer.parseInt((String) combo8.getSelectedItem());
        int num9 = Integer.parseInt((String) combo9.getSelectedItem());
        int num10 = Integer.parseInt((String) combo10.getSelectedItem());
        int num11 = Integer.parseInt((String) combo11.getSelectedItem());
        int num12 = Integer.parseInt((String) combo12.getSelectedItem());
        int num13 = Integer.parseInt((String) combo13.getSelectedItem());
        int num14 = Integer.parseInt((String) combo14.getSelectedItem());

        suma = num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8 + num9 + num10 + num11 + num12 + num13 + num14;
        txtGUI.setText(new Double(suma).toString());

    }

    public JTextField getTxtPFsinAjustar() {
        return txtPFsinAjustar;
    }

    public void setTxtPFsinAjustar(JTextField txtPFsinAjustar) {
        this.txtPFsinAjustar = txtPFsinAjustar;
    }

    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        combo1 = new javax.swing.JComboBox();
        combo2 = new javax.swing.JComboBox();
        combo3 = new javax.swing.JComboBox();
        combo4 = new javax.swing.JComboBox();
        combo5 = new javax.swing.JComboBox();
        combo6 = new javax.swing.JComboBox();
        combo7 = new javax.swing.JComboBox();
        combo8 = new javax.swing.JComboBox();
        combo9 = new javax.swing.JComboBox();
        combo10 = new javax.swing.JComboBox();
        combo11 = new javax.swing.JComboBox();
        combo12 = new javax.swing.JComboBox();
        combo13 = new javax.swing.JComboBox();
        combo14 = new javax.swing.JComboBox();
        txtGUI = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        botonFactordeAjuste = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtPFsinAjustar = new javax.swing.JTextField();
        botonVolver = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULAR FACTOR DE AJUSTE");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("1) ¿Requiere el sistema copias de seguridad y de recuperación fiables?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("2) ¿Se requiere comunicación de datos?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("3) ¿Existen funciones de procesamiento distribuido?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("4) ¿Es crítico el rendimiento?");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("5) ¿Se ejecutará el sistema en un entorno operativo existente y fuertemente utilizado?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("6) ¿Requiere el sistema entrada de datos interactiva?");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("7) ¿Requiere la entrada de datos interactiva que las transacciones de entrada se");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("lleven a cabo sobre múltiples pantallas u operaciones?");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("8) ¿Se actualizan los archivos maestros de forma interactiva?");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("9) ¿Son complejas las entradas, las salidas, los archivos o las peticiones?");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("10) ¿Es complejo el procesamiento interno?");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("11) ¿Se ha diseñado el código para ser reutilizable?");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("12) ¿Están incluidas en el diseño la conversación y la instalación?");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("13) ¿Se ha diseñado el sistema para soportar múltiples instalaciones en diferentes organizaciones?");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("14) ¿Se ha diseñado la aplicación para facilitar los cambios y para ser fácilmente utilizada por el usuario?");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("PREGUNTA:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 25, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 590, 40));

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("EVALUACIÓN:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel17))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 200, 40));

        combo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        combo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 66, -1));

        combo2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        combo2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(combo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 66, -1));

        combo3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        combo3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(combo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 67, -1));

        combo4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        combo4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(combo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 68, -1));

        combo5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        combo5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(combo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 68, -1));

        combo6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        combo6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo6ActionPerformed(evt);
            }
        });
        jPanel1.add(combo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 68, -1));

        combo7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        combo7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(combo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 68, -1));

        combo8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        combo8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(combo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 68, -1));

        combo9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        combo9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(combo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 68, -1));

        combo10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        combo10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combo10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo10ActionPerformed(evt);
            }
        });
        jPanel1.add(combo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 68, -1));

        combo11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        combo11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(combo11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 68, -1));

        combo12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        combo12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(combo12, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 68, -1));

        combo13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo13.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        combo13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(combo13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, 68, -1));

        combo14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo14.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        combo14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(combo14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 68, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 810, 520));

        txtGUI.setEditable(false);
        txtGUI.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtGUI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGUI.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtGUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 560, 99, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("a 5 (Absolutamente escencial)");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 600, 300, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("* Rango de 0 (No importante o no aplicable)");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 580, 420, -1));

        botonFactordeAjuste.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonFactordeAjuste.setText("OBTENER");
        botonFactordeAjuste.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonFactordeAjuste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFactordeAjusteActionPerformed(evt);
            }
        });
        getContentPane().add(botonFactordeAjuste, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, -1, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/botonSiguiente.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/botonSiguienteG.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(831, 547, 90, 90));

        txtPFsinAjustar.setEditable(false);
        txtPFsinAjustar.setBorder(null);
        getContentPane().add(txtPFsinAjustar, new org.netbeans.lib.awtextra.AbsoluteConstraints(858, 472, -1, -1));

        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/volverMenuPrincipal.png"))); // NOI18N
        botonVolver.setBorder(null);
        botonVolver.setBorderPainted(false);
        botonVolver.setContentAreaFilled(false);
        botonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolver.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/volverMenuPrincipalG.png"))); // NOI18N
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondo2.png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo6ActionPerformed

    private void combo10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo10ActionPerformed

    private void botonFactordeAjusteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFactordeAjusteActionPerformed
        calculoGI();
    }//GEN-LAST:event_botonFactordeAjusteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VentanaResultadosPuntosdeFuncion vr = new VentanaResultadosPuntosdeFuncion();
        vr.setVisible(true);
        vr.getTxtGI().setText(txtGUI.getText());
        vr.getTxtPuntosSinAjustar().setText(txtPFsinAjustar.getText());
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        VentanaPrincipal vp = new VentanaPrincipal();
        vp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonFactordeAjuste;
    private javax.swing.JButton botonVolver;
    private javax.swing.JComboBox combo1;
    private javax.swing.JComboBox combo10;
    private javax.swing.JComboBox combo11;
    private javax.swing.JComboBox combo12;
    private javax.swing.JComboBox combo13;
    private javax.swing.JComboBox combo14;
    private javax.swing.JComboBox combo2;
    private javax.swing.JComboBox combo3;
    private javax.swing.JComboBox combo4;
    private javax.swing.JComboBox combo5;
    private javax.swing.JComboBox combo6;
    private javax.swing.JComboBox combo7;
    private javax.swing.JComboBox combo8;
    private javax.swing.JComboBox combo9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtGUI;
    private javax.swing.JTextField txtPFsinAjustar;
    // End of variables declaration//GEN-END:variables
}
