/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.text.DecimalFormat;
import javax.swing.JTextField;

/**
 *
 * @author Examen Práctico #1
 */
public class VentanaResultadosPuntosdeCU extends javax.swing.JFrame {

    private double tf;
    private double ef;
    private double aw;
    private double ucw;
    private double resultadoTF;
    private double resultadoEF;

    DecimalFormat df = new DecimalFormat("###.###");

    /**
     * Creates new form VentanaFactordeAjuste
     */
    public VentanaResultadosPuntosdeCU() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public JTextField getTxtPesoAW() {
        return txtPesoAW;
    }

    public void setTxtPesoAW(JTextField txtPesoAW) {
        this.txtPesoAW = txtPesoAW;
    }

    public JTextField getTxtPesoEF() {
        return txtPesoEF;
    }

    public void setTxtPesoEF(JTextField txtPesoEF) {
        this.txtPesoEF = txtPesoEF;
    }

    public JTextField getTxtPesoTF() {
        return txtPesoTF;
    }

    public void setTxtPesoTF(JTextField txtPesoTF) {
        this.txtPesoTF = txtPesoTF;
    }

    public JTextField getTxtPesoUCW() {
        return txtPesoUCW;
    }

    public void setTxtPesoUCW(JTextField txtPesoUCW) {
        this.txtPesoUCW = txtPesoUCW;
    }

    public void calcularTotalFactoresTecnicos() {
        tf = Double.parseDouble(txtPesoTF.getText());
        double resultadoTF1 = (0.01) * tf;
        resultadoTF = resultadoTF1 + 0.6;
        String fresult = df.format(resultadoTF);
        txtCalculoTF.setText(fresult);
    }

    public void calcularTotalFactoresAmbientales() {
        ef = Double.parseDouble(txtPesoEF.getText());
        double resultadoEF1 = (-0.03) * ef;
        resultadoEF = resultadoEF1 + 1.4;
        txtCalculoEF.setText(new Double(resultadoEF).toString());
    }

    public void calcularPuntosdeCU() {
        aw = Double.parseDouble(txtPesoAW.getText());
        ucw = Double.parseDouble(txtPesoUCW.getText());
        double resultado = (aw + ucw) * resultadoTF * resultadoEF;
        String xresultado = df.format(resultado);
        txtCalculoPuntosCU.setText(xresultado);

    }

    public void calcularEsfuerzo() {
        double CU = Double.parseDouble(txtCalculoPuntosCU.getText());
        double esfuerzo = CU * 20;
        txtCalculoEsfuerzo.setText(new Double(esfuerzo).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPesoAW = new javax.swing.JTextField();
        txtPesoUCW = new javax.swing.JTextField();
        txtCalculoTF = new javax.swing.JTextField();
        txtCalculoEsfuerzo = new javax.swing.JTextField();
        txtCalculoEF = new javax.swing.JTextField();
        botonCalcular = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPesoEF = new javax.swing.JTextField();
        txtPesoTF = new javax.swing.JTextField();
        txtCalculoPuntosCU = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULO PUNTOS DE CASOS DE USO");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Calculo de factores ambientales:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Peso AW:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Peso UCW:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        txtPesoAW.setEditable(false);
        txtPesoAW.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtPesoAW.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPesoAW.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtPesoAW.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPesoAW.setFocusable(false);
        getContentPane().add(txtPesoAW, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 158, -1));

        txtPesoUCW.setEditable(false);
        txtPesoUCW.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtPesoUCW.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPesoUCW.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtPesoUCW.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPesoUCW.setFocusable(false);
        getContentPane().add(txtPesoUCW, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 158, -1));

        txtCalculoTF.setEditable(false);
        txtCalculoTF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCalculoTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCalculoTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtCalculoTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCalculoTF.setFocusable(false);
        getContentPane().add(txtCalculoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 160, 40));

        txtCalculoEsfuerzo.setEditable(false);
        txtCalculoEsfuerzo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtCalculoEsfuerzo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCalculoEsfuerzo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtCalculoEsfuerzo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCalculoEsfuerzo.setFocusable(false);
        getContentPane().add(txtCalculoEsfuerzo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 200, 50));

        txtCalculoEF.setEditable(false);
        txtCalculoEF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCalculoEF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCalculoEF.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtCalculoEF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCalculoEF.setFocusable(false);
        getContentPane().add(txtCalculoEF, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 176, 39));

        botonCalcular.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        botonCalcular.setText("Calcular");
        botonCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(botonCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 190, 40));

        botonVolver.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonVolver.setText("Aceptar");
        botonVolver.setBorder(null);
        botonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 570, 120, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Peso EF:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Calculo del esfuerzo:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        txtPesoEF.setEditable(false);
        txtPesoEF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtPesoEF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPesoEF.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtPesoEF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPesoEF.setFocusable(false);
        getContentPane().add(txtPesoEF, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 158, -1));

        txtPesoTF.setEditable(false);
        txtPesoTF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtPesoTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPesoTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtPesoTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPesoTF.setFocusable(false);
        getContentPane().add(txtPesoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 158, -1));

        txtCalculoPuntosCU.setEditable(false);
        txtCalculoPuntosCU.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtCalculoPuntosCU.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCalculoPuntosCU.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        txtCalculoPuntosCU.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCalculoPuntosCU.setFocusable(false);
        getContentPane().add(txtCalculoPuntosCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 200, 50));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Pesos obtenidos:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 190, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Horas/Hombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 120, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Calculo de los puntos de casos de uso:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Calculo de factores técnicos:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Peso TF:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondo10.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularActionPerformed
        calcularTotalFactoresAmbientales();
        calcularTotalFactoresTecnicos();
        calcularPuntosdeCU();
        calcularEsfuerzo();
    }//GEN-LAST:event_botonCalcularActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        VentanaPrincipal vp = new VentanaPrincipal();
        vp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalcular;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCalculoEF;
    private javax.swing.JTextField txtCalculoEsfuerzo;
    private javax.swing.JTextField txtCalculoPuntosCU;
    private javax.swing.JTextField txtCalculoTF;
    private javax.swing.JTextField txtPesoAW;
    private javax.swing.JTextField txtPesoEF;
    private javax.swing.JTextField txtPesoTF;
    private javax.swing.JTextField txtPesoUCW;
    // End of variables declaration//GEN-END:variables
}
